include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    avoid_types_on_closure_parameters: ignore
    cascade_invocations: ignore
    constant_identifier_names: ignore
    directives_ordering: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

formatter:
  page_width: 80
  trailing_commas: preserve
